/*
 * -------------------------------------------------------
 * Osa: Roolien Oikeudet (Role Permissions)
 * Määrittelee, mitkä sovelluksen oikeudet (app_permissions) kuuluvat mihinkin rooliin (roles).
 * -------------------------------------------------------
 */

-- Taulu: public.role_permissions
CREATE TABLE IF NOT EXISTS public.role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50) REFERENCES public.roles(name) ON DELETE CASCADE NOT NULL, -- Viittaus rooliin
    permission public.app_permissions NOT NULL, -- Mikä oikeus (ENUM)
    UNIQUE (role, permission) -- Varmistaa, ettei samaa oikeutta voi antaa roolille useasti
);

COMMENT ON TABLE public.role_permissions IS 'Määrittää oikeudet (permissions) kullekin roolille (role).';
COMMENT ON COLUMN public.role_permissions.role IS 'Rooli, johon oikeus liittyy.';
COMMENT ON COLUMN public.role_permissions.permission IS 'Myönnetty oikeus (app_permissions ENUM).';

-- Indeksit
CREATE INDEX IF NOT EXISTS ix_role_permissions_role ON public.role_permissions (role);

-- Oikeudet
-- service_role saa täydet oikeudet hallita roolien oikeuksia.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.role_permissions TO service_role;
-- Kirjautuneet käyttäjät saavat vain lukea roolien oikeuksia.
GRANT SELECT ON TABLE public.role_permissions TO authenticated;

-- Funktio: public.has_permission
-- Tarkistaa, onko käyttäjällä tietty oikeus tietyssä tilissä.
CREATE OR REPLACE FUNCTION public.has_permission (
  user_id UUID,
  account_id UUID,
  permission_name public.app_permissions
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE -- Funktio ei muuta dataa
SECURITY DEFINER -- Tarvitaan pääsy kaikkiin jäsenyyksiin ja rooli-oikeuksiin
SET search_path = '','public'
AS $$
BEGIN
    -- Tarkistetaan, löytyykö käyttäjältä jäsenyys tilillä, jonka roolilla on kyseinen oikeus.
    RETURN EXISTS (
        SELECT 1
        FROM public.accounts_memberships AS am
        JOIN public.role_permissions AS rp ON am.account_role = rp.role
        WHERE am.user_id = has_permission.user_id -- Viitataan funktion parametreihin
          AND am.account_id = has_permission.account_id
          AND rp.permission = permission_name
    );
END;
$$;

GRANT EXECUTE ON FUNCTION public.has_permission(UUID, UUID, public.app_permissions) TO authenticated, service_role;

-- Funktio: public.has_more_elevated_role
-- Tarkistaa, onko käyttäjän rooli hierarkisesti korkeampi kuin kohderooli.
-- HUOM: Sama logiikka sisältyy can_action_account_member -funktioon.
CREATE OR REPLACE FUNCTION public.has_more_elevated_role (
  check_user_id UUID, -- Käyttäjä, jonka roolia verrataan
  check_account_id UUID, -- Tili, jossa roolia verrataan
  target_role_name VARCHAR -- Rooli, johon verrataan
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER -- Tarvitaan pääsy rooleihin ja jäsenyyksiin
SET search_path = '','public'
AS $$
DECLARE
    user_hierarchy_level INT;
    target_hierarchy_level INT;
BEGIN
    -- Haetaan tarkistettavan käyttäjän roolin hierarkiataso
    SELECT r.hierarchy_level INTO user_hierarchy_level
    FROM public.accounts_memberships AS am
    JOIN public.roles AS r ON am.account_role = r.name
    WHERE am.account_id = check_account_id AND am.user_id = check_user_id;

    -- Haetaan kohderoolin hierarkiataso
    SELECT hierarchy_level INTO target_hierarchy_level
    FROM public.roles
    WHERE name = target_role_name;

    -- Jos jompaakumpaa tasoa ei löydy, palautetaan false
    IF user_hierarchy_level IS NULL OR target_hierarchy_level IS NULL THEN
        RETURN false;
    END IF;

    -- Palautetaan true, jos käyttäjän taso on pienempi (korkeampi) kuin kohderoolin taso
    RETURN user_hierarchy_level < target_hierarchy_level;
END;
$$;

GRANT EXECUTE ON FUNCTION public.has_more_elevated_role(UUID, UUID, VARCHAR) TO authenticated, service_role;

-- Funktio: public.has_same_role_hierarchy_level
-- Tarkistaa, onko käyttäjän rooli samalla hierarkiatasolla kuin kohderooli.
-- HUOM: Sama logiikka sisältyy can_action_account_member -funktioon.
CREATE OR REPLACE FUNCTION public.has_same_role_hierarchy_level (
  check_user_id UUID,
  check_account_id UUID,
  target_role_name VARCHAR
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER -- Tarvitaan pääsy rooleihin ja jäsenyyksiin
SET search_path = '','public'
AS $$
DECLARE
    user_hierarchy_level INT;
    target_hierarchy_level INT;
BEGIN
    -- Haetaan tarkistettavan käyttäjän roolin hierarkiataso
    SELECT r.hierarchy_level INTO user_hierarchy_level
    FROM public.accounts_memberships AS am
    JOIN public.roles AS r ON am.account_role = r.name
    WHERE am.account_id = check_account_id AND am.user_id = check_user_id;

    -- Haetaan kohderoolin hierarkiataso
    SELECT hierarchy_level INTO target_hierarchy_level
    FROM public.roles
    WHERE name = target_role_name;

    -- Jos jompaakumpaa tasoa ei löydy, palautetaan false
    IF user_hierarchy_level IS NULL OR target_hierarchy_level IS NULL THEN
        RETURN false;
    END IF;

    -- Palautetaan true, jos tasot ovat samat
    RETURN user_hierarchy_level = target_hierarchy_level;
END;
$$;

GRANT EXECUTE ON FUNCTION public.has_same_role_hierarchy_level(UUID, UUID, VARCHAR) TO authenticated, service_role;

-- RLS: public.role_permissions
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- Poistetaan vanha politiikka varmuuden vuoksi
DROP POLICY IF EXISTS "Kirjautuneet käyttäjät voivat lukea roolien oikeudet" ON public.role_permissions;

-- RLS-politiikka: Sallitaan kaikkien kirjautuneiden käyttäjien lukea kaikki rooli-oikeusmääritykset.
CREATE POLICY "Kirjautuneet käyttäjät voivat lukea roolien oikeudet" ON public.role_permissions
  FOR SELECT TO authenticated USING (true);
